name: Daily Games
on:
  schedule:
    # Every days: 5h00 UTC
    - cron: "0 5 * * *"
  # Allow manual testing
  workflow_dispatch:
jobs:
  post-games:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node index.mjs
        working-directory: daily-games
        env:
          DISCORD_WEBHOOK_DAILY_GAME_URL: ${{ secrets.DISCORD_WEBHOOK_DAILY_GAME_URL }}
          DISCORD_ROLE_ID_IRL: ${{ secrets.DISCORD_ROLE_ID_IRL }}